### ISSUE TITLE
MSbuild X64 error when signing the Click-one app.

### ISSUE THREAD

**Issue by cage200** [dotnet/msbuild#6121]
Hi guys, 
I have the following issue with MSBuild X64

### Issue Description

This is the minimal AzureDevOps build task. 
```
  - task: VSBuild@1
    displayName: 'Build'
    inputs:
      solution: '**\MySolution.sln'
      platform: 'any cpu'
      configuration: release
      msbuildArchitecture: x64
      msbuildArgs: '/target:publish'
```

If I build a Click-once application with **msbuildArchitecture: x64** I get the following error: 

`##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4157,5): Error MSB3482: An error occurred while signing: SignTool.exe was not found at path`

If I **remove** the x64 requirement for MSBuild and runs the X86 version **everything is fine**.

### Steps to Reproduce
Run a publish command for click-once using C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe 
instead of 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe

### Expected Behavior
Builds finishes without error and click-once is signed.

### Actual Behavior
It fails with error as it does not find the signtool.  It keeps looking for the signtool file in the project folder of the solution being built.

### Analysis
Probably some path resolve error for x64 version

### Versions & Configurations
Microsoft (R) Build Engine version 16.8.2+25e4d540b for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

16.8.2.56705

Windows 10 , X64

Thanks.
