### ISSUE TITLE
AzDO DotNetCoreCLI@2 task fails during pack

### ISSUE THREAD

**Issue by khamza85** [dotnet/msbuild#7872]
We installed MSBuild version 17.3.0+92e077650 in our build agent. Then this AzDO task started failing
```
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: MySolution.sln
    buildProperties: 'PackageVersion=$(PkgVersion)'
```

Here is what the AzDO task generates:
```
D:\VSTSAgentsWork\01\_tool\dotnet\dotnet.exe pack D:\VSTSAgentsWork\01\786\s\MySolution.sln --output D:\VSTSAgentsWork\01\786\a /p:Configuration=Release;PackageVersion=3.0.145385-beta --verbosity Normal
```
and this is the error we get
```
error MSB4126: The specified solution configuration "Release;PackageVersion=3.0.145385-beta|Any CPU" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration.
```

This however used to work with MSBuild version 17.2.0+41abc5629.

The only workaround is to use a custom command for DotNetCoreCLI@2 task:
```
- task: DotNetCoreCLI@2
  displayName: 'dotnet custom'
  inputs:
    command: custom
    projects: MySolution.sln
    custom: pack
    arguments: '-c $(BuildConfiguration) -p:PackageVersion=$(PkgVersion)-beta -v Normal -o $(Build.ArtifactStagingDirectory)'
```
