### ISSUE TITLE
[Broken Build]: MSB4249: Unable to build website project

### ISSUE THREAD

**Issue by jazwiecki** [dotnet/msbuild#9021]
### Issue Description

Trying to build an old web app with a GitHub action, and I've hit a wall using `dotnet/msbuild`. My background is Linux, and the creator of this project is long gone. I don't know what's not working, Googling for the error doesn't turn up much specific to using dotnet/msbuild in a GitHub action, and I'm not sure what else I can try. Any suggestions?

Goal is to build and deploy this project to a server.

### Steps to Reproduce

Here's the GitHub action:

```
on: [push]

name: Dotnet Build

jobs:

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.0.x
      # - name: Restore dependencies
      # run: dotnet build flipper.sln # <- MSB4249 error
      # - run: dotnet aspnet_compiler flipper.sln # <- MSB4249 error
      - run: dotnet msbuild aspnet_compiler flipper.sln # <- MSB4249 error
```

Here's the project file:

```
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.5.33424.131
MinimumVisualStudioVersion = 10.0.40219.1
Project("{E24C65DC-7377-472B-9ABA-BC803B73C61A}") = "flipper", "..\..\..\..\..\Temp\orderentry\flipper\", "{EC58CFAF-D64E-43AC-AB8C-22B2EF7D03DE}"
	ProjectSection(WebsiteProperties) = preProject
		TargetFrameworkMoniker = ".NETFramework,Version%3Dv4.0"
		Debug.AspNetCompiler.VirtualPath = "/localhost_49919"
		Debug.AspNetCompiler.PhysicalPath = "..\..\..\..\..\Temp\orderentry\flipper\"
		Debug.AspNetCompiler.TargetPath = "PrecompiledWeb\localhost_49919\"
		Debug.AspNetCompiler.Updateable = "true"
		Debug.AspNetCompiler.ForceOverwrite = "true"
		Debug.AspNetCompiler.FixedNames = "false"
		Debug.AspNetCompiler.Debug = "True"
		Release.AspNetCompiler.VirtualPath = "/localhost_49919"
		Release.AspNetCompiler.PhysicalPath = "..\..\..\..\..\Temp\orderentry\flipper\"
		Release.AspNetCompiler.TargetPath = "PrecompiledWeb\localhost_49919\"
		Release.AspNetCompiler.Updateable = "true"
		Release.AspNetCompiler.ForceOverwrite = "true"
		Release.AspNetCompiler.FixedNames = "false"
		Release.AspNetCompiler.Debug = "False"
		VWDPort = "49919"
	EndProjectSection
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{EC58CFAF-D64E-43AC-AB8C-22B2EF7D03DE}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{EC58CFAF-D64E-43AC-AB8C-22B2EF7D03DE}.Debug|Any CPU.Build.0 = Debug|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {94A1AA5A-CEA6-43D3-AA94-E5CB7D24DDA4}
	EndGlobalSection
EndGlobal
```

### Expected Behavior

Build completes successfully

### Actual Behavior

```
MSBuild version 17.6.3+07e294721 for .NET
D:\a\flipper\flipper\flipper.sln : Solution file error MSB4249: Unable to build website project "flipper". The ASP.NET compiler is only available on the .NET Framework version of MSBuild.
Error: Process completed with exit code 1.
```

### Ask us questions

What's the right way to build a .Net 4 project with a GitHub action?
