### ISSUE TITLE
[Build Warning]: MSB3178 for mstest dlls in a click once publish exe project

### ISSUE THREAD

**Issue by Lumoryel** [dotnet/msbuild#9561]
### Issue Description

On our Azure Devops Pipeline, we get the following warnings during the build process (msbuild) for an net framework 4.8 exe project that contains unit tests, using mstest. This project is also published using click once:

`##[warning]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4199,5): Warning MSB3178: Die C:\Users\tfsadmin.nuget\packages\mstest.testadapter\3.1.1\build\net462\..\_localization\de\Microsoft.TestPlatform.AdapterUtilities.resources.dll-Assembly wurde falsch als Datei angegeben.
`

The same warning happens for:

Microsoft.TestPlatform.CoreUtilities.resources.dll
Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.resources.dll
Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.resources.dll
Microsoft.VisualStudio.TestPlatform.ObjectModel.resources.dll
Microsoft.VisualStudio.TestPlatform.TestFramework.resources.dll

There are no warnings for a local build on our developer machines.

These are "localization files", could it have something to do with the fact that our devops build server runs on a german operating system?

Is there anything we can do here?

Posted my problem also here:
https://developercommunity.visualstudio.com/t/Pipeline-build-warnings-for-TestPlatform/10538416#T-ND10544129

### Steps to Reproduce

Too difficult to reproduce

### Expected Behavior

Build runs without warnings.

### Actual Behavior

MSB3178 Warnings are shown

**Comment by Lumoryel** [comment]
@sujitnayak no it only happens on the Devops pipeline, not on local computers. I guess the binlog would contain private information (all DLL names etc.) that I don't want to share public?

**Comment by sujitnayak** [comment]
@Lumoryel 

In that case, you would need to create a minimal sample that reproduces the error and share that.

The warning suggests that assembly references are being passed as file references to the ClickOnce msbuild task. You can also investigate this by generating the binlog and comparing with the log from the local computer to determine why these assemblies are being passes as files. You can search online for the 'msbuild binlog viewer' tool that can open these binlog files.

**Comment by Lumoryel** [comment]
I created a test app which makes those warnings on the build-server but not on a local machine:

[TestAppMSB3178.zip](https://github.com/dotnet/msbuild/files/13920412/TestAppMSB3178.zip)

- New WPF Application (.Net Framework)
- Add Nuget Reference for MSTest.TestAdapter and MSTest.TestFramework

I don't know if these things are necessary to get the warning but we have those settings in our productive project:

- Enable Click-Once Security Settings, "This is a full trust application"
- Publish "Install Mode and Settings" switched to "The Application is availble online only"

**Comment by sujitnayak** [comment]
@Lumoryel I assume you're seeing these AzDO pipeline. If so, could you please also provide the command line your task invokes in the pipeline?

**Comment by sujitnayak** [comment]
@Lumoryel 

I cannot reproduce the issue. I added your test project into a AzDO pipline with 3 tasks - NuGet Restore, MSBuild build and MSBuild publish. I don't get any 3178 MS warnings. 

Here are the definitions of the 3 tasks in my pipeline:

steps:
- task: **NuGetCommand**@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'src\scratch\TestApp\TestAppMSBuild3178.sln'
    feedsToUse: config
    nugetConfigPath: build/nuget.config

steps:
- task: **MSBuild**@1
  displayName: 'Build '
  inputs:
    solution: '**/TestAppMSBuild3178.csproj'
    msbuildArchitecture: x64
    configuration: Release

steps:
- task: **MSBuild**@1
  displayName: Publish
  inputs:
    solution: '**/TestAppMSBuild3178.csproj'
    msbuildArchitecture: x64
    configuration: Release
    msbuildArguments: '/t:publish'


You can look at the corresponding YAML for your tasks and paste that in your reply.

If there is no difference, we would need to see your msbuild binlog for the test app. For that, you would need to add '/bl' to your msbuildArguments in the pipeline and then send that to us.

Thanks.

**Comment by Lumoryel** [comment]
This is our yml:


```
  steps:
  - checkout: self
    clean: true
  - task: NuGetToolInstaller@1
    displayName: Use NuGet
    inputs:
      versionSpec: 5.9.1
  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      solution: WITec.Tests/TestAppMSB3178/TestAppMSB3178.sln
      selectOrConfig: config
      nugetConfigPath: nuget.config
  - task: VSBuild@1
    displayName: Build solution WITec.Tests/TestAppMSB3178/TestAppMSB3178.sln
    inputs:
      solution: WITec.Tests/TestAppMSB3178/TestAppMSB3178.sln
      msbuildArgs: -bl:C:\Users\tfsadmin\Desktop\WITecBuild.binlog
      maximumCpuCount: true
```


Attached also the binlog file.
[WITecBuild.zip](https://github.com/dotnet/msbuild/files/14095578/WITecBuild.zip)
